databases:
- engine: PG
  name: db
  num_nodes: 1
  size: db-s-dev-database
  version: "12"
name: python-boilerplate
region: ams
services:
- environment_slug: python
  envs:
  - key: ENV_VARIABLE
    scope: RUN_AND_BUILD_TIME
    value: VALUE
  - key: DATABASE_URL
    scope: RUN_TIME
    value: ${db.DATABASE_URL}
  github:
    branch: main
    deploy_on_push: true
    repo: gzog/python-do-app-boilerplate
  health_check:
    http_path: /
  http_port: 80
  instance_count: 1
  instance_size_slug: basic-xxs
  name: service
  routes:
  - path: /
  run_command: python web.py
workers:
- environment_slug: python
  envs:
  - key: ENV_VARIABLE
    scope: RUN_AND_BUILD_TIME
    value: VALUE
  - key: DATABASE_URL
    scope: RUN_TIME
    value: ${db.DATABASE_URL}
  github:
    branch: main
    deploy_on_push: true
    repo: gzog/python-do-app-boilerplate
  instance_count: 1
  instance_size_slug: basic-xxs
  name: worker
  run_command: python worker.py