name: python-boilerplate
region: ams
workers:
- environment_slug: python
  github:
    branch: main
    deploy_on_push: true
    repo: gzog/python-do-app-boilerplate
  instance_count: 1
  instance_size_slug: basic-xxs
  name: python-boilerplate
  run_command: python worker.py