name: python-boilerplate
services:
- environment_slug: python
  github:
    branch: main
    deploy_on_push: true
    repo: gzog/python-do-app-boilerplate
  name: python-boilerplate
  run_command: python web.py